In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import plotly.express as px
import glob
import spacy
import sys
sys.path.append('../../../../utils')
sys.path.append('..')
import gezi
from gezi import tqdm
from src.eval import calc_f1
pd.set_option('display.float_format', lambda x: '%.0f' % x)

In [2]:
v = '3'
mn= 'torch.20220102-075827'
model_dir = f'../working/online/{v}/{mn}'

In [3]:
import tensorflow as tf
from absl import flags
FLAGS = flags.FLAGS
from transformers import AutoTokenizer
from src import config
from src.torch_model import Model
from src.util import get_preds
import melt as mt
from datasets import Dataset
import torch
import lele
argv = open(f'{model_dir}/command.txt').readline().strip().split()
FLAGS(argv)
config.init_()
MAX_LEN = FLAGS.max_len
tokenizer = AutoTokenizer.from_pretrained(FLAGS.backbone, add_prefix_space=True)
model = Model()

ic| config.py:73 in init_()
    FLAGS.backbone: '../input/allenai/longformer-large-4096'
ic| config.py:79 in init_()- FLAGS.num_classes: 15
Some weights of the model checkpoint at ../input/allenai/longformer-large-4096 were not used when initializing LongformerModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing LongformerModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LongformerModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LongformerModel were not initialized from the model checkpoint at ../input/allenai/longformer-large-4096 and are newly initialized: ['longformer.pooler.dense.weight', 'longformer.pooler.dense.bias']
You should 

In [4]:
lele.load(model, f'{model_dir}/model.pt')

{'epoch': 3,
 'step': 2925,
 'state_dict': OrderedDict([('backbone.embeddings.position_ids',
               tensor([[   0,    1,    2,  ..., 4095, 4096, 4097]])),
              ('backbone.embeddings.word_embeddings.weight',
               tensor([[-1.2620e-01, -4.2589e-03,  3.6409e-02,  ...,  4.8356e-02,
                        -1.2965e-05, -3.8844e-02],
                       [ 7.7477e-03, -1.5526e-02,  1.5503e-02,  ..., -1.5518e-02,
                         2.2903e-02,  1.5526e-02],
                       [-7.4972e-02,  1.0324e-03, -1.1500e-01,  ...,  1.0446e-01,
                         6.5437e-02, -4.0188e-02],
                       ...,
                       [ 4.0131e-02,  1.6527e-03,  4.6051e-02,  ..., -2.4597e-02,
                        -4.8889e-02,  3.3844e-02],
                       [ 4.8706e-02,  2.6596e-02,  3.9307e-02,  ..., -3.5919e-02,
                        -1.1147e-02,  8.2779e-03],
                       [-1.5625e-02, -1.1894e-02, -2.3956e-02,  ...,  4.4464e-02,
 

In [5]:
# GET TEST TEXT IDS
files = os.listdir('../input/feedback-prize-2021/test')
TEST_IDS = [f.replace('.txt','') for f in files if 'txt' in f]
print('There are',len(TEST_IDS),'test texts.')

There are 5 test texts.


In [6]:
# CONVERT TEST TEXT TO TOKENS
test_tokens = np.zeros((len(TEST_IDS),MAX_LEN), dtype='int32')
test_attention = np.zeros((len(TEST_IDS),MAX_LEN), dtype='int32')
word_ids_list = []
for id_num in tqdm(range(len(TEST_IDS))):
    # READ TRAIN TEXT, TOKENIZE, AND SAVE IN TOKEN ARRAYS    
    n = TEST_IDS[id_num]
    # name = f'../input/feedback-prize-2021/train/{n}.txt'
    name = f'../input/feedback-prize-2021/test/{n}.txt'
    txt = open(name, 'r').read()
    encoding = tokenizer(txt.split(),
                        is_split_into_words=True,
                        padding='max_length', 
                        truncation=True, 
                        max_length=MAX_LEN)
    test_tokens[id_num,] = encoding['input_ids']
    test_attention[id_num,] = encoding['attention_mask']
    word_ids = encoding.word_ids()
    word_ids = [-1 if x is None else x for x in word_ids]
    word_ids_list.append(word_ids)

  0%|          | 0/5 [00:00<?, ?it/s]

In [7]:
 dataset = Dataset.from_dict({
   'input_ids': test_tokens,
   'attention_mask': test_attention
 })

In [8]:
dataset.set_format(type='torch')
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8)

In [9]:
p = lele.predict(model, dataloader)

  0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
# INFER TEST TEXTS
test_preds = np.argmax(p['pred'],axis=-1)
scores = gezi.softmax(p['pred'], axis=-1)

In [11]:
list(p.keys())

['pred']

In [12]:
test_preds

array([[10, 10,  9, ...,  3,  3,  3],
       [10, 10,  9, ...,  3,  3,  3],
       [10, 10,  9, ...,  3,  3,  3],
       [ 0, 10,  9, ...,  3,  3,  3],
       [10, 10,  9, ...,  3,  3,  3]])

In [13]:
if 'start_logits' in  p:
  test_preds = (test_preds, gezi.softmax(p['start_logits'], axis=-1))
df = get_preds(TEST_IDS, test_preds, word_ids_list, scores)

  0%|          | 0/5 [00:00<?, ?it/s]

In [14]:
df

id                 class  \
0   D46BCB48440A                  Lead   
1   D46BCB48440A              Position   
2   D46BCB48440A                 Claim   
3   D46BCB48440A                 Claim   
4   D46BCB48440A              Evidence   
5   D46BCB48440A              Evidence   
6   D46BCB48440A              Evidence   
7   D46BCB48440A  Concluding Statement   
8   DF920E0A7337                  Lead   
9   DF920E0A7337              Position   
10  DF920E0A7337                 Claim   
11  DF920E0A7337                 Claim   
12  DF920E0A7337                 Claim   
13  DF920E0A7337              Evidence   
14  DF920E0A7337              Evidence   
15  DF920E0A7337              Evidence   
16  DF920E0A7337  Concluding Statement   
17  18409261F5C2                  Lead   
18  18409261F5C2              Position   
19  18409261F5C2                 Claim   
20  18409261F5C2                 Claim   
21  18409261F5C2                 Claim   
22  18409261F5C2                 Claim   
23  18409261F5C2              Evidence   
24  18409261F5C2                 Claim   
25  18409261F5C2              Evidence   
26  18409261F5C2              Evidence   
27  18409261F5C2                 Claim   
28  18409261F5C2              Evidence   
29  0FB0700DAF44                  Lead   
30  0FB0700DAF44              Position   
31  0FB0700DAF44                 Claim   
32  0FB0700DAF44                 Claim   
33  0FB0700DAF44                 Claim   
34  0FB0700DAF44              Evidence   
35  0FB0700DAF44                 Claim   
36  0FB0700DAF44              Evidence   
37  0FB0700DAF44  Concluding Statement   
38  0FB0700DAF44  Concluding Statement   
39  D72CB1C11673                  Lead   
40  D72CB1C11673              Position   
41  D72CB1C11673                 Claim   
42  D72CB1C11673                 Claim   
43  D72CB1C11673                 Claim   
44  D72CB1C11673              Evidence   
45  D72CB1C11673              Evidence   
46  D72CB1C11673              Evidence   
47  D72CB1C11673  Concluding Statement   

                                     predictionstring  
0   0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19  
1                             20 21 22 23 24 25 26 27  
2                                            28 37 38  
3                                         39 40 41 42  
4   43 45 57 58 59 60 61 62 63 64 65 66 67 68 69 7...  
5   139 151 152 153 154 155 156 157 158 159 160 16...  
6   213 224 225 226 227 228 229 230 231 232 233 23...  
7   306 307 308 309 310 311 312 313 314 315 316 31...  
8   0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...  
9        68 69 70 71 72 73 74 75 76 77 78 79 80 81 82  
10                               83 85 86 87 88 89 90  
11                            91 92 93 94 95 96 97 98  
12                     99 101 102 103 104 105 106 107  
13  108 119 120 121 122 123 124 125 126 127 128 12...  
14  301 311 312 313 314 315 316 317 318 319 320 32...  
15  457 467 468 469 470 471 472 473 474 475 476 47...  
16  621 622 623 624 625 626 627 628 629 630 631 63...  
17  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...  
18  124 126 127 128 129 130 131 132 133 134 135 13...  
19                        138 140 141 142 143 144 145  
20                    146 147 148 149 150 151 152 153  
21                        154 156 157 158 159 160 161  
22                                175 176 177 178 179  
23                                        180 181 182  
24                                        183 184 185  
25  186 190 191 192 193 194 195 196 197 198 199 20...  
26  441 442 443 444 445 446 447 448 449 450 451 45...  
27  714 715 716 717 718 719 720 721 722 723 724 72...  
28  739 740 741 742 743 744 745 746 747 748 749 75...  
29  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...  
30                               41 42 43 44 45 46 47  
31    48 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64  
32  65 67 68 69 70 71 72 73 74 75 76 77 78 79 80 8...  
33  84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 9.

In [ ]:
df.to_csv(f'{model_dir}/submission.csv')